pipeline:
  nuget:
    image: dodoreg.azurecr.io/drone-plugins/nuget:1.0.1
    pull: true
    secrets: [ nuget_source, nuget_user, nuget_password, nuget_sourcename ]

  build:
    image: docker
    commands:
    - docker build . -t httpclientextensions -f Dockerfile
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [ push, pull_request ]
  
  push:
    image: docker
    commands:
    - docker run httpclientextensions --api-key $NUGET_PASSWORD 
    secrets: [ nuget_password ]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    when:
      status: [ success ]